### ISSUE TITLE
The Rust Backend of Inciteful

### ISSUE THREAD

**Issue by TheLostLambda** [inciteful-xyz/inciteful-web#26]
Hello!

It's lovely to see the frontend of this fantastic application is open source! I'd love to contribute at some point, but I'll admit I'm probably more up to speed on Rust than I am most web development.

I remember reading on Reddit someplace that the backend of the app was written in Rust? I was wondering if there were still plans to open-source that / if you could use any contributor help tidying things up before it's made fully public. I'm happy to help work on things there :) I've written some scary code before, but I find refactoring Rust rather enjoyable (certainly not a claim I can make about every language I've worked with :sweat_smile:)

Let me know what you think (and thanks a ton for such a wonderful tool!)

**Comment by weishuhn** [comment]
Thanks for the interest!  I'm definitely planning on open sourcing it soon.  I'm just now getting back to working on Inciteful after a hiatus spent working on another project.  I hope to have it ready in the next month.  I'll let you know when I do.
