### ISSUE TITLE
Authors' name incorrectly recognized

### ISSUE THREAD

**Issue by AsgeologeekFan** [inciteful-xyz/inciteful-web#43]
Hi,

Thank you for this excellent tool!
I have met a small bug when I import the papers with Chinese author. This happens regardless if I use the Zotero plugin or if I paste the DOI on the website.
There are many similar cases. Some examples are as followed:

DOI: 10.1007/s10064-019-01658-0
Real author: Zhenping **Zhang** | Qian Sheng | Xiaodong Fu | Yongqiang Zhou | **Juehao** Huang | **Yuxiang** Du
Inciteful: Zhenping **Zhu** | Qian Sheng | Xiaodong Fu | Yongqiang Zhou | **Jun** Huang | **Yonggang** Du

DOI: 10.1016/j.tust.2019.04.017
The fourth author is **Yu Liang**, but Inciteful shows **Lintao Yu** .

I'm very grateful for your efforts.

**Comment by AsgeologeekFan** [comment]
Hi,

Thank you for this excellent tool! 
I have met a small bug when I import the papers with Chinese author. This happens regardless if I use the Zotero plugin or if I paste the DOI on the website.
There are many similar cases. Some examples are as followed:

- DOI: 10.1007/s10064-019-01658-0
Real author: Zhenping **Zhang** | Qian Sheng | Xiaodong Fu | Yongqiang Zhou | **Juehao** Huang | **Yuxiang** Du 
Inciteful: Zhenping **Zhu** | Qian Sheng | Xiaodong Fu | Yongqiang Zhou | **Jun** Huang | **Yonggang** Du

- DOI: 10.1016/j.tust.2019.04.017
The fourth author is **Yu Liang**, but Inciteful shows **Lintao Yu** .

 I'm very grateful for your efforts.

**Comment by weishuhn** [comment]
Sorry for the delay on this.  But I get most of my metadata (as do others) from OpenAlex and it seems like they have it wrong there:  https://api.openalex.org/works/https://doi.org/10.1007/s10064-019-01658-0

You should contact them, then once they fix it, it will be fixed on more than just my site.
